#!/bin/bash

shopt -s expand_aliases

##
## Check if we need sudo
##
$(docker ps &> /dev/null)
if [ "${?}" != "0" ]; then
  set_alias () { alias mydocker="sudo docker"; }
else
  set_alias () { alias mydocker="docker"; }
fi;
set_alias

##
## Begin App
##

resp=$(mydocker ps --quiet --all --filter="name=dsyelp")
repos=$(realpath -e "$(pwd)/../")

if [ "${resp}" = "" ]; then
  mydocker run \
    --publish="80:80" \
    --add-host='dsyelp.local:127.0.0.1' \
    --privileged \
    --cap-add='ALL' \
    --volume="${repos}:/App/repos" \
    --detach \
    --tty \
    --interactive \
    --name='dsyelp' \
    dsyelp;
else
  mydocker start dsyelp
fi;

