#!/bin/bash

CURRDIR="$(dirname "${0}")"
source "${CURRDIR}/lib"

##
## Begin App
##

repo=$(python -c 'import os, sys; sys.stdout.write(os.path.abspath(sys.argv[1]) + "\n")' "${CURRDIR}/../")
cont_id=$(mydocker ps --quiet --all --filter="name=dsyelp")

##
## Container does not exist, so build it
##
if [ "${cont_id}" = "" ]; then
  mydocker run \
    --publish="9191:80" \
    --add-host='dsyelp.local:127.0.0.1' \
    --privileged \
    --cap-add='ALL' \
    --volume="${repo}:/App/repos/dsyelp" \
    --detach \
    --tty \
    --rm \
    --interactive \
    --name='dsyelp' \
    dsyelp;
##
## Container does exist so start it up
##
else
  mydocker start dsyelp
fi;

